services:
  redis:
    image: redis:latest
    container_name: image-pipeline-redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy noeviction

  postgres:
    image: postgres:17
    container_name: image-pipeline-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image_pipeline
    ports:
      - "5433:5432"
    volumes:
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: quay.io/minio/minio
    container_name: image-pipeline-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 minioadmin minioadmin; do
        echo 'Waiting for MinIO...';
        sleep 1;
      done;
      mc mb -p local/image-pipeline || true;
      echo 'Bucket initialized';
      "

  api:
    build:
      context: ../..
      dockerfile: api/Dockerfile
    container_name: image-pipeline-api
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_QUEUE_NAME: jobs

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: image_pipeline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      OBJECT_STORAGE_ENDPOINT: http://minio:9000
      OBJECT_STORAGE_BUCKET: image-pipeline
      OBJECT_STORAGE_ACCESS_KEY: minioadmin
      OBJECT_STORAGE_SECRET_KEY: minioadmin

      MAX_QUEUE_LENGTH: 100 # Development default, needs to be adjusted empirically
    depends_on:
      - redis
      - postgres
      - minio
      - minio-init

  worker-default:
    build:
      context: ../..
      dockerfile: worker/Dockerfile
    container_name: image-pipeline-worker-default
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_QUEUE_NAME: jobs:default
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: image_pipeline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      OBJECT_STORAGE_ENDPOINT: http://minio:9000
      OBJECT_STORAGE_BUCKET: image-pipeline
      OBJECT_STORAGE_ACCESS_KEY: minioadmin
      OBJECT_STORAGE_SECRET_KEY: minioadmin
    depends_on:
      - redis
      - postgres
      - minio
      - minio-init

  worker-heavy:
    build:
      context: ../..
      dockerfile: worker/Dockerfile
    container_name: image-pipeline-worker-heavy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_QUEUE_NAME: jobs:heavy
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: image_pipeline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      OBJECT_STORAGE_ENDPOINT: http://minio:9000
      OBJECT_STORAGE_BUCKET: image-pipeline
      OBJECT_STORAGE_ACCESS_KEY: minioadmin
      OBJECT_STORAGE_SECRET_KEY: minioadmin
    depends_on:
      - redis
      - postgres
      - minio
      - minio-init
